### ISSUE TITLE
[ERROR] Could not resolve "crypto", "querystring", "querystring", "stream",  and "util"

### ISSUE THREAD

**Issue by TheBestOrNothing** [fanout/js-grip#34]
When using js-grip to build one WebSocket-over-HTTP server, the following error occur.  Node.js verions is v18.19.0 and npm version 9.9.2. Could you please tell how to fix the error when building with js-compute-runtime command? thanks.

> js-compute-runtime ./src/index.js ./bin/main.wasm

 [ERROR] Could not resolve "querystring"

    node_modules/@fanoutio/grip/build/src/utilities/grip.js:28:41:
      28 │ const querystring = __importStar(require("querystring"));
         ╵                                          ~~~~~~~~~~~~~

  The package "querystring" wasn't found on the file system but is built into node. Are you trying
  to bundle for node? You can use "platform: 'node'" to do that, which will remove this error.

 [ERROR] Could not resolve "stream"

    node_modules/jws/lib/sign-stream.js:5:21:
      5 │ var Stream = require('stream');
        ╵                      ~~~~~~~~

  The package "stream" wasn't found on the file system but is built into node. Are you trying to
  bundle for node? You can use "platform: 'node'" to do that, which will remove this error.

 [ERROR] Could not resolve "util"

    node_modules/jws/lib/sign-stream.js:7:19:
      7 │ var util = require('util');
        ╵                    ~~~~~~

  The package "util" wasn't found on the file system but is built into node. Are you trying to
  bundle for node? You can use "platform: 'node'" to do that, which will remove this error.

 [ERROR] Could not resolve "crypto"

    node_modules/jwa/index.js:3:21:
      3 │ var crypto = require('crypto');
        ╵                      ~~~~~~~~

  The package "crypto" wasn't found on the file system but is built into node. Are you trying to
  bundle for node? You can use "platform: 'node'" to do that, which will remove this error.

 [ERROR] Could not resolve "url"

    node_modules/@fanoutio/grip/build/src/utilities/grip.js:29:33:
      29 │ const url = __importStar(require("url"));
         ╵                                  ~~~~~

  The package "url" wasn't found on the file system but is built into node. Are you trying to bundle
  for node? You can use "platform: 'node'" to do that, which will remove this error.

/home/whisper/fastly/fanout-forward/node_modules/esbuild/lib/main.js:1636
  let error = new Error(`${text}${summary}`);
              
Error: Build failed with 13 errors:
node_modules/@fanoutio/grip/build/src/utilities/grip.js:28:41: ERROR: Could not resolve "querystring"
node_modules/@fanoutio/grip/build/src/utilities/grip.js:29:33: ERROR: Could not resolve "url"
node_modules/@fanoutio/grip/build/src/utilities/http.js:27:41: ERROR: Could not resolve "querystring"
node_modules/jsonwebtoken/sign.js:12:65: ERROR: Could not resolve "crypto"
node_modules/jsonwebtoken/verify.js:9:62: ERROR: Could not resolve "crypto"
...

**Comment by harmony7** [comment]
Hi, thanks for reaching out.

When you're using Fastly Compute and you need to use a module such as this one that depends on Node modules (like 'querystring', 'url', and 'crypto', in your case), you'll need to use a bundler such as Webpack to apply polyfills.

[This section on the Fastly Developer Site](https://developer.fastly.com/learning/compute/javascript/#module-bundling) describes adding Webpack to do this.

The basic idea is:
1. Add a `prebuild` script to package.json to run `webpack`. This takes your './src/index.js` and converts it into e.g. `./build/index.js`.

2. As it does this, it replaces those calls to the Node modules with JavaScript polyfill code that simulates those modules. Use `webpack.config.js` to specify the polyfills.

3. Modify your js-compute-runtime call so that it calls into the bundle. `js-compute-runtime ./build/index.js ./bin/main.wasm`

For a specific example, you may want to take a look at https://github.com/fastly/fanout-compute-js-demo/tree/main/src/origin.

I'm closing this because it's not an issue but rather a question. If you need further help, feel free to follow up with a question. Or, you may also try the [Fastly Community Forum](https://community.fastly.com), where you may find answers or get replies more quickly.
